# Generated by Django 5.0.6 on 2024-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=50)),
                ("task_description", models.CharField(max_length=200)),
                ("author_name", models.CharField(max_length=50)),
                ("author_email", models.EmailField(max_length=50)),
                ("task_assigned_to", models.CharField(max_length=50)),
                ("task_status", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
